# Generated by Django 2.2.9 on 2020-12-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.IntegerField(choices=[(0, 'SAN MARCOS')], default=0)),
                ('municipio', models.IntegerField(choices=[(0, 'SAN PEDRO')], default=0)),
                ('identificador', models.IntegerField(choices=[(0, 'AREA RURAL'), (1, 'AREA URBANA'), (2, 'LLANO GRANDE')])),
                ('zona', models.IntegerField(blank=True, choices=[(0, ''), (1, 'ZONA 1'), (2, 'ZONA 1 Y 2'), (3, 'ZONA 1 Y 4'), (4, 'ZONA 2'), (5, 'ZONA 4'), (6, 'ZONA 3 Y 4')], default=0)),
                ('caserio', models.IntegerField(blank=True, choices=[(0, ''), (1, 'LOS JAZMINES'), (2, 'LLANO GRANDE')], default=0)),
                ('canton', models.IntegerField(blank=True, choices=[(0, ''), (1, 'LA PARROQUIA'), (2, 'SANTA MARIA DE ATOCHA'), (3, 'SAN MIGUEL'), (4, 'SAN JUAN DE DIOS'), (5, 'SAN JUAN DEL POZO'), (6, 'SAN AGUSTÍN TONALÁ'), (7, 'EL MOSQUITO'), (8, 'SAN SEBASTIÁN')], default=0)),
                ('sector', models.IntegerField(blank=True, choices=[(0, ''), (1, 'HIERBA BUENA'), (2, 'GALLO ROJO')], default=0)),
                ('aldeas', models.IntegerField(blank=True, choices=[(0, ''), (1, 'CANTEL'), (2, 'CORRAL GRANDE'), (3, 'CHAMPOLLAP'), (4, 'CHIM'), (5, 'EL CEDRO'), (6, 'EL TABLERO'), (7, 'LA GRANDEZA'), (8, 'MÁVIL'), (9, 'PIEDRA GRANDE'), (10, 'PROVINCIA CHIQUITA'), (11, 'SACUCHÚM'), (12, 'SAN ANDRÉS CHÁPIL'), (13, 'SAN ISIDRO CHAMAC'), (14, 'SAN JOSÉ CÁBEN'), (15, 'SAN PEDRO PETZ'), (16, 'SANTA TERESA'), (17, 'SAN FRANCISCO SOCHE')], default=0)),
                ('paraje', models.CharField(blank=True, max_length=20)),
                ('nombre_grupo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Asiganacion de grupos',
                'verbose_name_plural': 'Asiganacion de grupos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('tercer_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20)),
                ('apellido_casada', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=8)),
                ('direccion', models.CharField(blank=True, max_length=20)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Registro de personas',
                'verbose_name_plural': 'Registro de personas',
            },
        ),
        migrations.CreateModel(
            name='RelacionDPG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.IntegerField(choices=[(0, 'PRESIDENTE'), (1, 'VICE-PRESIDENTE'), (2, 'SECRETARIA'), (3, 'TESORERA'), (4, 'VOCAL 1'), (5, 'VOCAL 2')])),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_directiva', to='inicio.Grupo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_directiva', to='inicio.Persona')),
            ],
            options={
                'verbose_name': 'Asignar Directiva',
                'verbose_name_plural': 'Asignar Directiva',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='integrantes',
            field=models.ManyToManyField(to='inicio.Persona'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.IntegerField(choices=[(0, 'CURSO'), (1, 'TALLER'), (2, 'SEMINARIO'), (3, 'DIPLOMADO'), (4, 'CAPACITACION'), (5, 'CONVERSATORIO')])),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('de', models.IntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')])),
                ('a', models.IntegerField(choices=[(0, 'LUNES'), (1, 'MARTES'), (2, 'MIERCOLES'), (3, 'JUEVES'), (4, 'VIERNES'), (5, 'SABADO'), (6, 'DOMINGO')])),
                ('integrantes', models.ManyToManyField(to='inicio.Persona')),
            ],
        ),
    ]
