# Generated by Django 2.2.9 on 2021-02-15 03:27

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.IntegerField(choices=[(0, 'SAN MARCOS')], default=0)),
                ('municipio', models.IntegerField(choices=[(0, 'SAN PEDRO')], default=0)),
                ('identificador', models.IntegerField(choices=[(0, ''), (1, 'AREA RURAL'), (2, 'AREA URBANA'), (3, 'LLANO GRANDE')])),
                ('zona', models.IntegerField(blank=True, choices=[(0, ''), (1, 'ZONA 1'), (2, 'ZONA 1 Y 2'), (3, 'ZONA 1 Y 4'), (4, 'ZONA 2'), (5, 'ZONA 4'), (6, 'ZONA 3 Y 4')], default=0)),
                ('caserio', models.IntegerField(blank=True, choices=[(0, ''), (1, 'LOS JAZMINES'), (2, 'LLANO GRANDE')], default=0)),
                ('canton', models.IntegerField(blank=True, choices=[(0, ''), (1, 'LA PARROQUIA'), (2, 'SANTA MARIA DE ATOCHA'), (3, 'SAN MIGUEL'), (4, 'SAN JUAN DE DIOS'), (5, 'SAN JUAN DEL POZO'), (6, 'SAN AGUSTÍN TONALÁ'), (7, 'EL MOSQUITO'), (8, 'SAN SEBASTIÁN')], default=0)),
                ('sector', models.IntegerField(blank=True, choices=[(0, ''), (1, 'HIERBA BUENA'), (2, 'GALLO ROJO')], default=0)),
                ('aldeas', models.IntegerField(blank=True, choices=[(0, ''), (1, 'CANTEL'), (2, 'CORRAL GRANDE'), (3, 'CHAMPOLLAP'), (4, 'CHIM'), (5, 'EL CEDRO'), (6, 'EL TABLERO'), (7, 'LA GRANDEZA'), (8, 'MÁVIL'), (9, 'PIEDRA GRANDE'), (10, 'PROVINCIA CHIQUITA'), (11, 'SACUCHÚM'), (12, 'SAN ANDRÉS CHÁPIL'), (13, 'SAN ISIDRO CHAMAC'), (14, 'SAN JOSÉ CÁBEN'), (15, 'SAN PEDRO PETZ'), (16, 'SANTA TERESA'), (17, 'SAN FRANCISCO SOCHE')], default=0)),
                ('paraje', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Canichel'), (2, 'Joya del Porvenir'), (3, 'El Plan'), (4, 'Ajil'), (5, 'Buena Vista'), (6, 'San Francisco'), (7, 'Agua Caliente'), (8, 'El Zapote'), (9, 'La Industria'), (10, 'El Tesoro'), (11, 'Las Flores'), (12, 'Vista Hermosa'), (13, 'La Libertad'), (14, 'Los Bravo'), (15, 'La Ciénaga'), (16, 'Alta Vista'), (17, 'San Rafael'), (18, 'La Comunidad l'), (19, 'Carolina'), (20, 'Kusinché'), (21, 'Santa Rita I'), (22, 'Santa Rita II'), (23, 'Los Coyotes'), (24, 'Agua Bendita'), (25, 'La Michada'), (26, 'La Providencia'), (27, 'López'), (28, 'El Zarco'), (29, 'Villa El Progreso'), (30, 'El Carmen'), (31, 'Esquipulas'), (32, 'Ixcá'), (33, 'Las Escobas'), (34, 'San Lorenzo'), (35, 'San Miguel'), (36, 'San Martín'), (37, 'San Pedrito'), (38, 'La Caballería'), (39, 'Ojo de Agua'), (40, 'Villa Nueva'), (41, 'Cerro Grande'), (42, 'Las Piedrecitas'), (43, 'Paraje Agua Tibia'), (44, 'Sector Monterrey'), (45, 'Sector Tres Fuentes'), (46, 'Sector Los Ramírez'), (47, 'Sector Fraternidad')], default=0)),
                ('direccion_alternativa', models.CharField(blank=True, max_length=50)),
                ('nombre_grupo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Asiganacion de grupos',
                'verbose_name_plural': 'Asiganacion de grupos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=20, unique='true')),
                ('sexo', models.IntegerField(choices=[(0, ''), (1, 'M'), (2, 'F')], default=0)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20)),
                ('tercer_nombre', models.CharField(blank=True, max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20)),
                ('apellido_casada', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=8)),
                ('direccion', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPersonaGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.IntegerField(choices=[(0, 'MIEMBRO'), (1, 'PRESIDENTE'), (2, 'VICE-PRESIDENTE'), (3, 'SECRETARIA'), (4, 'TESORERA'), (5, 'VOCAL 1'), (6, 'VOCAL 2')], default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_directiva', to='inicio.Grupo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_directiva', to='inicio.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(0, 'Administrador'), (1, 'Trabajador Social'), (2, 'Tecnico Capacitador'), (3, 'Promotor de grupos sociales'), (5, 'Secretaria')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
