# Generated by Django 2.2.9 on 2020-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.IntegerField(choices=[(0, ''), (1, 'M'), (2, 'F')], default=0),
        ),
    ]
