# Generated by Django 2.2.9 on 2021-02-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='identificador',
            field=models.IntegerField(choices=[(0, ''), (1, 'AREA RURAL'), (2, 'AREA URBANA'), (3, 'LLANO GRANDE')]),
        ),
    ]
