# Generated by Django 2.2.9 on 2020-12-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_persona_sexo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
