# Generated by Django 2.2.9 on 2021-02-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20210210_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='direccion_alternativa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='paraje',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Canichel'), (2, 'Joya del Porvenir'), (3, 'El Plan'), (4, 'Ajil'), (5, 'Buena Vista'), (6, 'San Francisco'), (7, 'Agua Caliente'), (8, 'El Zapote'), (9, 'La Industria'), (10, 'El Tesoro'), (11, 'Las Flores'), (12, 'Vista Hermosa'), (13, 'La Libertad'), (14, 'Los Bravo'), (15, 'La Ciénaga'), (16, 'Alta Vista'), (17, 'San Rafael'), (18, 'La Comunidad l'), (19, 'Carolina'), (20, 'Kusinché'), (21, 'Santa Rita I'), (22, 'Santa Rita II'), (23, 'Los Coyotes'), (24, 'Agua Bendita'), (25, 'La Michada'), (26, 'La Providencia'), (27, 'López'), (28, 'El Zarco'), (29, 'Villa El Progreso'), (30, 'El Carmen'), (31, 'Esquipulas'), (32, 'Ixcá'), (33, 'Las Escobas'), (34, 'San Lorenzo'), (35, 'San Miguel'), (36, 'San Martín'), (37, 'San Pedrito'), (38, 'La Caballería'), (39, 'Ojo de Agua'), (40, 'Villa Nueva'), (41, 'Cerro Grande'), (42, 'Las Piedrecitas'), (43, 'Paraje Agua Tibia'), (44, 'Sector Monterrey'), (45, 'Sector Tres Fuentes'), (46, 'Sector Los Ramírez'), (47, 'Sector Fraternidad')], default=0),
        ),
    ]
