# Generated by Django 2.2.9 on 2021-01-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20210125_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionpersonagrupo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
    ]
