# Generated by Django 2.2.9 on 2021-01-08 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_delete_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='integrantes',
        ),
    ]
