# Generated by Django 2.2.9 on 2021-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_delete_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='integrantes',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre_grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relaciondpg',
            name='puesto',
            field=models.IntegerField(choices=[(0, 'MIEMBRO'), (1, 'PRESIDENTA(E)'), (2, 'VICE-PRESIDENTA(E)'), (3, 'SECRETARIA(O)'), (4, 'TESORERA(O)'), (5, 'VOCAL 1'), (6, 'VOCAL 2')], default=0),
        ),
    ]
