# Generated by Django 2.2.9 on 2021-02-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20210211_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cui',
            field=models.CharField(max_length=20, unique='true'),
        ),
    ]
