# Generated by Django 2.2.9 on 2021-02-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20210217_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionpersonagrupo',
            name='puesto',
            field=models.IntegerField(choices=[(0, 'MIEMBRO'), (1, 'PRESIDENTE'), (2, 'VICE-PRESIDENTE'), (3, 'SECRETARIA'), (4, 'TESORERA'), (5, 'VOCAL 1'), (6, 'VOCAL 2'), (7, 'VOCAL 3'), (8, 'VOCAL 4')], default=0),
        ),
    ]
