# Generated by Django 2.2.9 on 2021-01-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_grupo_integrantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre_grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='relaciondpg',
            name='puesto',
            field=models.IntegerField(choices=[(0, 'MIEMBRO'), (1, 'PRESIDENTE'), (2, 'VICE-PRESIDENTE'), (3, 'SECRETARIA'), (4, 'TESORERA'), (5, 'VOCAL 1'), (6, 'VOCAL 2')], default=0),
        ),
    ]
