# Generated by Django 2.2.9 on 2021-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20210211_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
