# Generated by Django 2.2.9 on 2021-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20210219_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
