# Generated by Django 2.2.9 on 2021-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20210108_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciondpg',
            name='puesto',
            field=models.IntegerField(choices=[(0, 'MIEMBRO'), (1, 'PRESIDENTA(E)'), (2, 'VICE-PRESIDENTA(E)'), (3, 'SECRETARIA(O)'), (4, 'TESORERA(O)'), (5, 'VOCAL 1'), (6, 'VOCAL 2')], default=0),
        ),
    ]
