# Generated by Django 2.2.9 on 2021-03-09 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20210222_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
