# Generated by Django 2.2.9 on 2020-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='a',
            field=models.IntegerField(choices=[(1, 'LUNES'), (2, 'MARTES'), (3, 'MIERCOLES'), (4, 'JUEVES'), (5, 'VIERNES'), (6, 'SABADO'), (7, 'DOMINGO')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='de',
            field=models.IntegerField(choices=[(1, 'LUNES'), (2, 'MARTES'), (3, 'MIERCOLES'), (4, 'JUEVES'), (5, 'VIERNES'), (6, 'SABADO'), (7, 'DOMINGO')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.IntegerField(choices=[(1, 'CURSO'), (2, 'TALLER'), (3, 'SEMINARIO'), (4, 'DIPLOMADO'), (5, 'CAPACITACION'), (6, 'CONVERSATORIO')]),
        ),
    ]
