# Generated by Django 2.2.9 on 2021-01-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='integrantes',
        ),
    ]
