# Generated by Django 2.2.9 on 2021-01-26 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20210126_0352'),
        ('servicios', '0002_remove_curso_integrantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_curso', to='servicios.Curso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_curso', to='inicio.Persona')),
            ],
        ),
    ]
