# Generated by Django 2.2.9 on 2021-01-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20210108_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='integrantes',
            field=models.ManyToManyField(blank=True, null=True, to='inicio.Persona'),
        ),
    ]
