# Generated by Django 2.2.9 on 2021-01-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20210115_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='integrantes',
            field=models.ManyToManyField(blank=True, to='inicio.Persona'),
        ),
    ]
