# Generated by Django 2.2.9 on 2021-01-26 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0003_auto_20210126_0352'),
        ('servicios', '0003_relacioncurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eje_trabajo', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('presupuesto', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('beneficiados', models.IntegerField()),
                ('resultado', models.CharField(max_length=150)),
                ('eje_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eje_servicios', to='reportes.Eje')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_id', to='servicios.Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_servicio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteGrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
                ('resultado', models.CharField(max_length=150)),
                ('beneficiados', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('eje_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eje_grupos', to='reportes.Eje')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_id', to='inicio.Grupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_grupo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
