# Generated by Django 2.2.9 on 2021-02-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegrupos',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='reporteservicios',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
