# Generated by Django 2.2.9 on 2020-12-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mujeresalfa',
            name='comunidad',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
