# Generated by Django 2.2.9 on 2021-02-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mujeresalfa',
            name='aprobados',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mujeresalfa',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
