# Generated by Django 2.2.9 on 2021-02-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0003_auto_20210218_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mujeresalfa',
            name='nombre_alfabetizadora',
            field=models.CharField(max_length=100),
        ),
    ]
