# Generated by Django 2.2.9 on 2020-12-28 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0003_auto_20201222_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name': 'Agregar Comunidades', 'verbose_name_plural': 'Agregar Comunidades'},
        ),
    ]
