# Generated by Django 2.2.9 on 2021-02-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0004_auto_20210222_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='comunidad',
            field=models.CharField(max_length=50),
        ),
    ]
