# Generated by Django 2.2.9 on 2021-02-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0005_auto_20210222_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={},
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='comunidad',
            field=models.IntegerField(choices=[(0, 'SAN JOSE'), (1, 'LA PARROQUIA'), (2, 'CENTRO')]),
        ),
    ]
