# Generated by Django 2.2.9 on 2021-02-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfabetizacion', '0006_auto_20210223_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name': 'Agregar Comunidades', 'verbose_name_plural': 'Agregar Comunidades'},
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='comunidad',
            field=models.CharField(max_length=50),
        ),
    ]
